config/routes.rb
Rails.application.routes.draw do
   resources :students
  root to: "students#index"
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #Users::ConfirmationController
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
has_one_attached :image
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      #before_action :authenticate_user!

#before_action :configure_permitted_parameters, if: :devise_controller?

#protected

# def configure_permitted_parameters
 ## devise_parameter_sanitizer.permit(:sign_up, keys: [:role_id, :first_name, :lastname, :image])
#end


end

app/controllers/confirmation_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  private
    def after_confirmation_path_for(resource_name, resource)
     sign_up(resource)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action:set_student, only:[:show, :edit, :update, :destroy]

def index
    @students = Student.all
end
def show
end
def new
    @student = Student.new
end
def create
    @student = Student.new(student_params)
    @student.save
    flash.alert = "User Added Successfully"
    redirect_to :action => :index
end
def edit
end
def update
    @student.update(student_params)
    redirect_to :action => :index
end
def destroy
    @student.destroy
    redirect_to :action => :index
end
private
def student_params
    params.require(:student).permit(:name, :age, :image)
end

def set_student
    @student = Student.find(params[:id])
end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
 devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmation_helper.rb
module ConfirmationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/postts_helper.rb
module PosttsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/home/home.html.erb
<ul>
  <% if user_signed_in? %>
    <h1>Welcome to the Website</h1>
<p>My email is <%= current_user.id %></p>
<p>My email is <%= current_user.email %></p>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>

  <% else %>
    <li>Sign In</li>
    <li>Sign Up</li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Update A new Student</h1>

<%= form_for @student, local: true do |f| %>
  <div class = "form-group mt-4">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>

    <%= f.label :age %><br/>
    <%= f.text_field :age %>

       <%= f.label :image %><br/>
    <%= f.file_field :image %>
  </div>
<br><%= f.submit "update", class: 'btn btn-primary mt-4' %>
  </div>
<% end %>
<%= link_to 'Back', {:action => 'index'} %>

app/views/students/index.html.erb
<ul>
  <% if user_signed_in? %>
    <h1>All Users</h1>
    <h1>Welcome to the Website</h1>
<p>My id is <%= current_user.id %></p>
<p>My email is <%= current_user.email %></p>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <ol>
<% @students.each do |user|  %>
<li><%= link_to user.name, student_path(user), method: 'get' %></li>
<%= button_to 'Delete', student_path(user), method: 'delete'%>
<%= button_to 'Edit', edit_student_path(user), method: 'get'%>
<%end%>
</ol>

  <% else %>
  <h1>Plaese Login into the website First</h1>

    <li><%= link_to 'Sign IN', 'users/sign_in'%></li>
    <li><%= link_to 'Sign UP', 'users/sign_up' %></li>
     <% end %>
</ul>

app/views/students/new.html.erb
<h1>Create A new Student</h1>

<%= form_for @student, local: true do |f| %>
  <div class = "form-group mt-4">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>

    <%= f.label :age %><br/>
    <%= f.text_field :age %>

    <%= f.label :image %><br/>
    <%= f.file_field :image %>
  </div>
<br><%= f.submit "Save", class: 'btn btn-primary mt-4' %>
  </div>
<% end %>
<%= link_to 'Back', {:action => 'index'} %>

app/views/students/show.html.erb
<h1>Student Details</h1>
<p><%= @student.id%></p>
<p><%= @student.name%></p>
<p><%= @student.age%></p>
<%= image_tag @student.image %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>